from fileSansPrio import File

f1 = File()
f2 = File()
f1.enfiler(5)
f1.enfiler(9)
f2.enfiler(1)
f1.enfiler(3)
print(f1)
f2.enfiler(f1.defiler())
f2.enfiler(f1.defiler())
f2.enfiler(7)
f2.enfiler(f1.defiler())
print(f1.estVide())
print(f2)
